import { Photo } from './types';

// Using picsum images but with specific IDs to maintain consistency
export const MOCK_PHOTOS: Photo[] = [
  {
    id: '1',
    url: 'https://picsum.photos/id/10/2500/1667',
    thumbnail: 'https://picsum.photos/id/10/800/533',
    title: 'Misty Forest Morning',
    location: 'Olympic National Park, USA',
    category: 'Nature',
    width: 2500,
    height: 1667,
    visualDescription: 'A moody forest scene with fog rolling through mossy trees and a calm river flowing in the foreground.',
    exif: {
      camera: 'Sony A7R IV',
      lens: 'FE 24-70mm GM',
      iso: 100,
      aperture: 'f/8.0',
      shutter: '1/60s',
      focalLength: '35mm',
      date: '2023-10-15',
    },
  },
  {
    id: '2',
    url: 'https://picsum.photos/id/15/2500/1667',
    thumbnail: 'https://picsum.photos/id/15/800/533',
    title: 'Waterfall Solitude',
    location: 'Iceland',
    category: 'Landscape',
    width: 2500,
    height: 1667,
    visualDescription: 'A powerful waterfall cascading over dark basalt rocks under a dramatic cloudy sky.',
    exif: {
      camera: 'Canon EOS R5',
      lens: 'RF 15-35mm L',
      iso: 50,
      aperture: 'f/11',
      shutter: '0.5s',
      focalLength: '15mm',
      date: '2023-09-22',
    },
  },
  {
    id: '3',
    url: 'https://picsum.photos/id/20/3670/2462',
    thumbnail: 'https://picsum.photos/id/20/800/537',
    title: 'Urban Geometry',
    location: 'Tokyo, Japan',
    category: 'Architecture',
    width: 3670,
    height: 2462,
    visualDescription: 'Minimalist architecture detail showing books and shelves in a library with warm lighting.',
    exif: {
      camera: 'Leica Q2',
      lens: 'Summilux 28mm',
      iso: 400,
      aperture: 'f/2.8',
      shutter: '1/125s',
      focalLength: '28mm',
      date: '2024-01-10',
    },
  },
  {
    id: '4',
    url: 'https://picsum.photos/id/28/4928/3264',
    thumbnail: 'https://picsum.photos/id/28/800/530',
    title: 'The Lonely Pine',
    location: 'Yosemite, USA',
    category: 'Nature',
    width: 4928,
    height: 3264,
    visualDescription: 'A scenic forest landscape with pine trees and mountains in the background.',
    exif: {
      camera: 'Nikon Z9',
      lens: 'Nikkor Z 70-200mm',
      iso: 200,
      aperture: 'f/5.6',
      shutter: '1/200s',
      focalLength: '105mm',
      date: '2023-11-05',
    },
  },
  {
    id: '5',
    url: 'https://picsum.photos/id/42/3456/2304',
    thumbnail: 'https://picsum.photos/id/42/800/533',
    title: 'Morning Coffee',
    location: 'Studio',
    category: 'Still Life',
    width: 3456,
    height: 2304,
    visualDescription: 'Abstract view of a coffee table with light and shadows creating geometric patterns.',
    exif: {
      camera: 'Fujifilm GFX 100S',
      lens: 'GF 80mm',
      iso: 160,
      aperture: 'f/4.0',
      shutter: '1/60s',
      focalLength: '80mm',
      date: '2024-02-14',
    },
  },
  {
    id: '6',
    url: 'https://picsum.photos/id/48/5000/3333',
    thumbnail: 'https://picsum.photos/id/48/800/533',
    title: 'Silicon Valley',
    location: 'California, USA',
    category: 'Technology',
    width: 5000,
    height: 3333,
    visualDescription: 'Dark moody shot of laptop components and tech gear on a desk.',
    exif: {
      camera: 'Sony A7S III',
      lens: 'FE 35mm GM',
      iso: 800,
      aperture: 'f/1.4',
      shutter: '1/100s',
      focalLength: '35mm',
      date: '2023-12-01',
    },
  },
  {
    id: '7',
    url: 'https://picsum.photos/id/54/3264/2176',
    thumbnail: 'https://picsum.photos/id/54/800/533',
    title: 'Mountain Range',
    location: 'Swiss Alps',
    category: 'Landscape',
    width: 3264,
    height: 2176,
    visualDescription: 'Foggy layers of blue mountains fading into the distance.',
    exif: {
      camera: 'Canon EOS R3',
      lens: 'RF 100-500mm',
      iso: 100,
      aperture: 'f/9.0',
      shutter: '1/400s',
      focalLength: '300mm',
      date: '2023-08-18',
    },
  },
  {
    id: '8',
    url: 'https://picsum.photos/id/60/1920/1200',
    thumbnail: 'https://picsum.photos/id/60/800/500',
    title: 'Office Life',
    location: 'New York, USA',
    category: 'Street',
    width: 1920,
    height: 1200,
    visualDescription: 'Top down view of a desk with computer and office supplies, clean aesthetic.',
    exif: {
      camera: 'Ricoh GR IIIx',
      lens: 'Integrated',
      iso: 400,
      aperture: 'f/2.8',
      shutter: '1/60s',
      focalLength: '40mm',
      date: '2024-03-01',
    },
  },
   {
    id: '9',
    url: 'https://picsum.photos/id/76/4912/3264',
    thumbnail: 'https://picsum.photos/id/76/800/532',
    title: 'Winter Cabin',
    location: 'Aspen, USA',
    category: 'Architecture',
    width: 4912,
    height: 3264,
    visualDescription: 'A small wooden cabin covered in snow during a calm winter day.',
    exif: {
      camera: 'Sony A7R V',
      lens: 'FE 50mm GM',
      iso: 200,
      aperture: 'f/2.0',
      shutter: '1/1000s',
      focalLength: '50mm',
      date: '2024-01-20',
    },
  },
];
