/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ParseConfig {
  maxThumbSize?: number
  thumbQuality?: number
  blurThreshold?: number
  enableRegionResolve?: boolean
  generateThumbVariants?: boolean
  parseProfile?: string
}
export interface FormatReport {
  declaredMime: string
  detectedMime: string
  converted: boolean
  reason: string
}
export interface ProcessingTaskMetric {
  taskId: string
  status: string
  durationMs: number
  degraded?: boolean
}
export interface ParseImageResult {
  normalizedOriginalBytes: Buffer
  normalizedOriginalMime: string
  normalizedOriginalFilename: string
  thumbBytes: Buffer
  thumbVariants: Record<string, Buffer>
  metadata: any
  formatReport: FormatReport
  stageMetrics: Array<ProcessingTaskMetric>
}
export declare function parseImageFromPath(path: string, declaredMime?: string | undefined | null, config?: ParseConfig | undefined | null): Promise<ParseImageResult>
export declare function parseImageFromBytes(fileName: string, mimeType: string, bytes: Buffer, config?: ParseConfig | undefined | null): Promise<ParseImageResult>
export declare function computeSha256(bytes: Buffer): string
export declare function computeThumbhash(width: number, height: number, rgba: Buffer): string | null
