/* auto-generated by NAPI-RS */

export interface ParseConfig {
  maxThumbSize?: number;
  thumbQuality?: number;
  blurThreshold?: number;
  enableRegionResolve?: boolean;
  generateThumbVariants?: boolean;
}

export interface FormatReport {
  declaredMime: string;
  detectedMime: string;
  converted: boolean;
  reason: string;
}

export interface ProcessingTaskMetric {
  taskId: string;
  status: string;
  durationMs: number;
  degraded?: boolean;
}

export interface ParseImageResult {
  normalizedOriginalBytes: Buffer;
  normalizedOriginalMime: string;
  normalizedOriginalFilename: string;
  thumbBytes: Buffer;
  thumbVariants: Record<string, Buffer>;
  metadata: {
    schema_version: string;
    image_id: string;
    thumbhash?: string;
    original_filename: string;
    timestamps: {
      created_at: string;
      client_processed_at: string;
    };
    files: {
      original: {
        path: string;
        mime: string;
        bytes: number;
      };
      thumb: {
        path: string;
        mime: string;
        bytes: number;
        width: number;
        height: number;
      };
      thumb_variants: Record<
        string,
        {
          path: string;
          mime: string;
          bytes: number;
          width: number;
          height: number;
          size: number;
        }
      >;
    };
    exif?: {
      Make?: string;
      Model?: string;
      LensModel?: string;
      DateTimeOriginal?: string;
      ExposureTime?: number;
      FNumber?: number;
      ISO?: number;
      FocalLength?: number;
      Orientation?: number;
      Software?: string;
      Artist?: string;
      Copyright?: string;
    };
    privacy: {
      original_contains_gps: boolean;
      exif_gps_removed: boolean;
    };
    geo?: {
      region: {
        country: string;
        province: string;
        city: string;
        display_name: string;
        cache_key: string;
        source: string;
        resolved_at: string;
      };
    };
    derived: {
      dimensions: {
        width: number;
        height: number;
      };
      dominant_color: {
        hex: string;
      };
      blur: {
        score: number;
        is_blurry: boolean;
        method: string;
      };
      phash: {
        algo: string;
        bits: number;
        value: string;
      };
      ocr: {
        status: string;
        summary?: string;
      };
    };
    processing: {
      summary: {
        total_ms: number;
        concurrency_profile: string;
        stage_durations: Array<{
          stage_id: string;
          duration_ms: number;
        }>;
      };
    };
  };
  formatReport: FormatReport;
  stageMetrics: ProcessingTaskMetric[];
}

/**
 * Parse image from file path, generate metadata and thumbnails
 */
export function parseImageFromPath(
  path: string,
  declaredMime?: string | null,
  config?: ParseConfig | null
): Promise<ParseImageResult>;

/**
 * Parse image from memory bytes
 */
export function parseImageFromBytes(
  fileName: string,
  mimeType: string,
  bytes: Buffer,
  config?: ParseConfig | null
): Promise<ParseImageResult>;

/**
 * Compute SHA256 hash with prefix
 */
export function computeSha256(bytes: Buffer): string;

/**
 * Compute thumbhash from RGBA data
 */
export function computeThumbhash(
  width: number,
  height: number,
  rgba: Buffer
): string | null;
