import { SharePosterInput } from "@/features/photos/types/map";

interface PosterStats {
  provinceCount: number;
  cityCount: number;
  districtCount: number;
}

const CANVAS_WIDTH = 1920;
const CANVAS_HEIGHT = 1080;

const formatDateStamp = (): string => {
  const now = new Date();
  const year = now.getFullYear();
  const month = String(now.getMonth() + 1).padStart(2, "0");
  const day = String(now.getDate()).padStart(2, "0");
  return `${year}${month}${day}`;
};

const uniqueCount = (values: string[]): number => new Set(values.filter(Boolean)).size;

const buildStats = (input: SharePosterInput): PosterStats => {
  const provinces = input.regionAggregates.map((item) => item.region.province);
  const cities = input.regionAggregates.map((item) => item.region.city);
  const districts = input.regionAggregates.map((item) => item.region.district);
  return {
    provinceCount: uniqueCount(provinces),
    cityCount: uniqueCount(cities),
    districtCount: uniqueCount(districts),
  };
};

const drawGlowTitle = (ctx: CanvasRenderingContext2D): void => {
  ctx.save();
  ctx.fillStyle = "#f4d7a3";
  ctx.font = "700 88px 'SF Pro Display', 'Segoe UI', sans-serif";
  ctx.shadowColor = "rgba(244, 215, 163, 0.42)";
  ctx.shadowBlur = 24;
  ctx.fillText("Travel Footprint", 130, 170);
  ctx.restore();
};

const drawMetaPanel = (
  ctx: CanvasRenderingContext2D,
  input: SharePosterInput,
  stats: PosterStats
): void => {
  ctx.fillStyle = "rgba(6, 8, 12, 0.72)";
  ctx.fillRect(98, 218, 760, 376);

  ctx.strokeStyle = "rgba(255, 255, 255, 0.16)";
  ctx.lineWidth = 1.2;
  ctx.strokeRect(98, 218, 760, 376);

  ctx.fillStyle = "rgba(255,255,255,0.88)";
  ctx.font = "500 34px 'SF Pro Display', 'Segoe UI', sans-serif";
  ctx.fillText("Places I've Been", 130, 286);

  ctx.fillStyle = "rgba(255,255,255,0.76)";
  ctx.font = "400 24px 'SF Pro Display', 'Segoe UI', sans-serif";
  ctx.fillText(`Time Range: ${input.timeRangeLabel}`, 130, 332);
  ctx.fillText(`Photo Points: ${input.visiblePointsCount}`, 130, 370);
  ctx.fillText(`Provinces Covered: ${stats.provinceCount}`, 130, 408);
  ctx.fillText(`Cities Covered: ${stats.cityCount}`, 130, 446);
  ctx.fillText(`Districts Covered: ${stats.districtCount}`, 130, 484);

  ctx.fillStyle = "rgba(244, 215, 163, 0.95)";
  ctx.font = "500 20px 'SF Pro Display', 'Segoe UI', sans-serif";
  ctx.fillText("TOP Regions", 130, 534);
};

const drawTopRegions = (ctx: CanvasRenderingContext2D, input: SharePosterInput): void => {
  const topRegions = [...input.regionAggregates]
    .sort((a, b) => b.count - a.count)
    .slice(0, 8);

  ctx.font = "400 19px 'SF Pro Display', 'Segoe UI', sans-serif";
  topRegions.forEach((item, index) => {
    const x = 130 + (index >= 4 ? 360 : 0);
    const y = 568 + (index % 4) * 34;
    ctx.fillStyle = "rgba(255,255,255,0.86)";
    ctx.fillText(`${String(index + 1).padStart(2, "0")}  ${item.region.displayName}`, x, y);
  });
};

const drawBrandLine = (ctx: CanvasRenderingContext2D): void => {
  ctx.fillStyle = "rgba(255,255,255,0.48)";
  ctx.font = "400 18px 'SF Pro Display', 'Segoe UI', sans-serif";
  ctx.fillText("Generated by Lumina · Travel Footprint", 130, CANVAS_HEIGHT - 72);
};

export async function buildMapSharePoster(input: SharePosterInput): Promise<{ blob: Blob; filename: string }> {
  const output = document.createElement("canvas");
  output.width = CANVAS_WIDTH;
  output.height = CANVAS_HEIGHT;

  const ctx = output.getContext("2d");
  if (!ctx) {
    throw new Error("Unable to create poster canvas");
  }

  ctx.drawImage(input.mapCanvas, 0, 0, CANVAS_WIDTH, CANVAS_HEIGHT);

  const darkOverlay = ctx.createLinearGradient(0, 0, 0, CANVAS_HEIGHT);
  darkOverlay.addColorStop(0, "rgba(5, 8, 14, 0.12)");
  darkOverlay.addColorStop(0.5, "rgba(5, 8, 14, 0.32)");
  darkOverlay.addColorStop(1, "rgba(5, 8, 14, 0.78)");
  ctx.fillStyle = darkOverlay;
  ctx.fillRect(0, 0, CANVAS_WIDTH, CANVAS_HEIGHT);

  drawGlowTitle(ctx);
  const stats = buildStats(input);
  drawMetaPanel(ctx, input, stats);
  drawTopRegions(ctx, input);
  drawBrandLine(ctx);

  const blob = await new Promise<Blob | null>((resolve) => output.toBlob(resolve, "image/png"));
  if (!blob) {
    throw new Error("Failed to export poster");
  }

  return {
    blob,
    filename: `lumina-footprint-${formatDateStamp()}.png`,
  };
}
